[package]
name = "av-denoise"
version = "0.1.0"
edition = "2024"
description = "Fast and efficient video denoising using accelerated nlmeans."

[[bin]]
name = "av-denoise"
path = "src/bin/main.rs"
required-features = ["binary", "ffms2", "stdin"]

[dependencies]
anyhow = "1"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = "0.3"
strum_macros = "0.28"
strum = "0.28"
bon = "3"

serde = { version = "1", features = ["derive"] }
cubecl = { version = "0.10", features = ["std"] }

# Frame ingestion via ffms2
ffms2 = { version = "0.3", optional = true }
av-scenechange = { version = "0.23", optional = true, features = ["ffms2"] }

# Frame ingestion via y4m stdin
y4m = { version = "0.8", optional = true }

# Binary dependencies
clap = { version = "4", optional = true, features = ["derive"] }
mimalloc = { version = "0.1", optional = true, default-features = false }#

[dev-dependencies]
futures = "0.3"

[features]
vulkan = ["cubecl/vulkan"]
metal = ["cubecl/metal"]
cuda = ["cubecl/cuda"]
rocm = ["cubecl/hip"]
cpu = ["cubecl/cpu"]
default = ["cpu", "vulkan"]
binary = ["clap", "mimalloc"]
ffms2 = ["dep:ffms2", "av-scenechange"]
stdin = ["y4m"]

[[bench]]
name = "nlmeans"
harness = false
required-features = ["clap"]

[[bench]]
name = "bench_kernels"
harness = false
required-features = ["clap"]
